In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [ ]:
train = pd.read_csv("/Train_2.csv")
test = pd.read_csv("/Test_2.csv")

In [ ]:
train.head()

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,Kenya,2018,uniqueid_1,Yes,Rural,Yes,3,24,Female,Spouse,Married/Living together,Secondary education,Self employed
1,Kenya,2018,uniqueid_2,No,Rural,No,5,70,Female,Head of Household,Widowed,No formal education,Government Dependent
2,Kenya,2018,uniqueid_3,Yes,Urban,Yes,5,26,Male,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,Kenya,2018,uniqueid_4,No,Rural,Yes,5,34,Female,Head of Household,Married/Living together,Primary education,Formally employed Private
4,Kenya,2018,uniqueid_5,No,Urban,No,8,26,Male,Child,Single/Never Married,Primary education,Informally employed

In [ ]:
test.head()

,country,year,uniqueid,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,Kenya,2018,uniqueid_6056,Urban,Yes,3,30,Male,Head of Household,Married/Living together,Secondary education,Formally employed Government
1,Kenya,2018,uniqueid_6060,Urban,Yes,7,51,Male,Head of Household,Married/Living together,Vocational/Specialised training,Formally employed Private
2,Kenya,2018,uniqueid_6065,Rural,No,3,77,Female,Parent,Married/Living together,No formal education,Remittance Dependent
3,Kenya,2018,uniqueid_6072,Rural,No,6,39,Female,Head of Household,Married/Living together,Primary education,Remittance Dependent
4,Kenya,2018,uniqueid_6073,Urban,No,3,16,Male,Child,Single/Never Married,Secondary education,Remittance Dependent

In [ ]:
print("shape for train data: ", train.shape)
print("shape for test data:", test.shape)

shape for train data:  (23524, 13)
shape for test data: (10086, 12)

In [ ]:
print("Train data dtypes: ", train.dtypes)
print("Test data dtypes: ", test.dtypes)

Train data dtypes:  country                   object
year                       int64
uniqueid                  object
bank_account              object
location_type             object
cellphone_access          object
household_size             int64
age_of_respondent          int64
gender_of_respondent      object
relationship_with_head    object
marital_status            object
education_level           object
job_type                  object
dtype: object
Test data dtypes:  country                   object
year                       int64
uniqueid                  object
location_type             object
cellphone_access          object
household_size             int64
age_of_respondent          int64
gender_of_respondent      object
relationship_with_head    object
marital_status            object
education_level           object
job_type                  object
dtype: object

In [ ]:
print("Train data nulls: ", train.isna().sum())
print("Test data nulls: ", test.isna().sum())

Train data nulls:  country                   0
year                      0
uniqueid                  0
bank_account              0
location_type             0
cellphone_access          0
household_size            0
age_of_respondent         0
gender_of_respondent      0
relationship_with_head    0
marital_status            0
education_level           0
job_type                  0
dtype: int64
Test data nulls:  country                   0
year                      0
uniqueid                  0
location_type             0
cellphone_access          0
household_size            0
age_of_respondent         0
gender_of_respondent      0
relationship_with_head    0
marital_status            0
education_level           0
job_type                  0
dtype: int64

In [ ]:
print("Train data duplicates: ", train.duplicated().sum())
print("Test data duplicates: ", test.duplicated().sum())

Train data duplicates:  0
Test data duplicates:  0

In [ ]:
##function to change bank to int
def bank(df):
  if df=='Yes':
    return 1
  else:
    return 0

In [ ]:
train['bank_account']=train['bank_account'].apply(bank)

In [ ]:
# Drop columns that won't be used for training
train= train.drop(['uniqueid'], axis=1)

# Separate features and target
X = train.drop(['bank_account'], axis=1)
y = train['bank_account']

In [ ]:
# Perform one-hot encoding using pd.get_dummies()
X_encoded = pd.get_dummies(X, drop_first=True)  # drop_first=True to avoid multicollinearity

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

In [ ]:
# Define the neural network model
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=X_train.shape[1]),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1)])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train,epochs=30)

Epoch 1/30
589/589 [==============================] - 2s 2ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 2/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 3/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 4/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 5/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 6/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 7/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 8/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 9/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 10/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 11/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 12/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 13/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 14/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 15/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 16/30
589/589 [==============================] - 1s 2ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 17/30
589/589 [==============================] - 1s 2ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 18/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 19/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 20/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 21/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 22/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 23/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 24/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 25/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 26/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 27/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 28/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 29/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581
Epoch 30/30
589/589 [==============================] - 1s 1ms/step - loss: 2.1885 - accuracy: 0.8581

In [ ]:
#model evaluate